#!/bin/sh
# v2017-12-11/00

instdir=$(dirname $(readlink $0))
src=$instdir/src
pkg=$src/io/github/yoshirulz/jtysh
inst=$pkg/JTyshInstantiation.java
out=$instdir/out/production/JTysh
mkdir -p $out

# Make -s(hell) supercede everything
if [ "$1" = "-s" ]; then
	while true; do ./jty.sh -i; done
	exit 0
fi

cat $pkg/header.java.txt >$inst
case "$1" in
	"-f")
		awk '{print"\t\t"$0}' "$2" >>$inst;;
	"-i")
		while read l; do
			if [ -n "$l" ]; then printf "\t\t%s\n" "$l" >>$inst; else break; fi
		done;;
	*)
		for l in "$@"; do
			if [ -n "$l" ]; then printf "\t\t%s\n" "$l" >>$inst; fi
		done;;
esac
cat $pkg/footer.java.txt >>$inst
javac -sourcepath $src -d $out $pkg/Main.java
java -classpath $out io.github.yoshirulz.jtysh.Main
